### PR TITLE
added functionality for multiple arguments and handled path

### PR DESCRIPTION
**Pull request by thewisepeter**
Hello. have a look through
1. So i have handled multiple arguments.
2. Also we can handle both "/bin/ls" and "ls"
3. our execute command has grown, we now have execute_functions file
4. I grouped string handling functions in one file strings.c

### CODE REVIEW

**Review by maqamylee0 — COMMENTED** [review]
1. last test ls -l /tmp not working.
Solution:  I found a fix that seemed to solve the problem of ls -l /tmp not working
1. In the functions that checks if the command has a slash, the for loop condition is causing an infinite [loop.ie](http://loop.ie/) strchr.c
2. I think it should be s[i] != 0 instead of s[i] >= 0. It seemed to work once I corrected this.

The reasoning is that in the comparison, the null terminator character evaluates to zero so the loop will always be true.

Cheers!

**Comment by thewisepeter** [comment]
ookay. i didnt even see that and i can't seem to even find the function. 

I have been fixated on the seg fault issue. all through the day i kept correcting an i finally fixed it. However some files have been deleted like execute_func. look through and see.

**Comment by thewisepeter** [comment]
hey. i saw that in the strchr func. however i still cant run ls -l /tmp. fails with invalid pointer error

**Comment by thewisepeter** [comment]
i have added functionality for exit and env. i still have failed to handle ls -l /tmp though.

**Review by maqamylee0 — APPROVED** [review]
Seems to be working now.Leme merge and test again to see.

**Pull request merged**
